export default [
  {
    id: "project1",
    name: "Food Delivery App (React Native)",
    imageURL: [
      "/assets/projects/foodash1.jpeg",
      "/assets/projects/foodash2.jpeg",
      "/assets/projects/foodash3.jpeg",
      "/assets/projects/foodash4.jpeg",
    ],
    videoURL: "/assets/foodashvid.mp4",
    description:
      "FoodDash is a demo React Native mobile application that allows users to discover and order food from local restaurants. It leverages the power of the Yelp Fusion API to provide real-time restaurant data, reviews, and menu information.",
    techs: [
      "React Native",
      "Expo for Development",
      "Yelp Fusion API",
      "Redux for state management",
      "React Navigation for routing",
      "Firebase Firestore to store order data",
      "Lottie to show animations",
    ],
    features: [
      "User can select different cities",
      "User can view, like, different restaurants in a particular city",
      "Ratings, Menu, Price range(cheap to expensive) of a restaurant is shown",
      "User can order food",
      "User Add to Cart",
      "Increment/Decrement Quantity",
      "Price and Total price changes accordingly",
      "Remove a selected item from cart",
      "More features soon",
    ],
    tags: [
      "React Native",
      "Yelp Fusion API",
      "Redux",
      "React Navigation",
      "Expo",
      "Firebase Firestore",
    ],
    github: "https://github.com/irf0/foodash-react-native-app",
  },

  {
    id: "project2",
    name: "Ecommerce App for Shoes (React Native)",
    imageURL: [
      "/assets/projects/shoe1.jpeg",
      "/assets/projects/shoe2.jpeg",
      "/assets/projects/shoe3.jpeg",
      "/assets/projects/shoe4.jpeg",
      "/assets/projects/shoe5.jpeg",
      "/assets/projects/shoe6.jpeg",
      "/assets/projects/shoe7.jpeg",
      "/assets/projects/shoe8.jpeg",
      "/assets/projects/shoe9.jpeg",
      "/assets/projects/shoe10.jpeg",
    ],
    videoURL: "/assets/nikevid.mp4",
    description:
      "Impulse Sneaxx is a cutting-edge mobile e-commerce application designed for shoe enthusiasts. Developed using the MERN (MongoDB, Express.js, React Native, Node.js) stack, this app provides a seamless and user-friendly experience for buying shoes online.",

    tags: [
      "React Native",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Expo",
      "React Navigation",
      "Redux",
      "REST API",
      "Stripe",
    ],
    techs: [
      "React Native",
      "Expo for development",
      "React Navigation",
      "React Async Storage for local storage",
      "Reduxjs toolkit for state management",
      "REST API",
      "MongoDB for database",
      "NodeJS/ExpressJS for backend",
      "Stripe for Payment",
    ],

    features: [
      "User can view, swipe left/right (carousel) products",
      "User can select and add to cart",
      "User can search and select a product",
      "User can Increment/Decrement quantity",
      "Price and Total price changes accordingly",
      "User can pay using Stripe secure payment",
      "User gets a tracking number after order completes",
      "User can see the tracking details directly or by entering the order id",
    ],
    github: "https://github.com/irf0/NikeFrontend",
  },
];
