export default [
  {
    id: "project1",
    name: "Workforce Rider App (React Native)",
    imageURL: [
      "/assets/projects/work1.png",
      "/assets/projects/work2.png",
      "/assets/projects/work3.png",
      "/assets/projects/work4.png",
      "/assets/projects/work5.png",
      "/assets/projects/work6.png",
      "/assets/projects/work7.png",
      "/assets/projects/work8.png",
      "/assets/projects/work9.png",
      "/assets/projects/work10.jpeg",
    ],
    videoURL: "/assets/workvid.mp4",
    description:
      "Workforce Riders is a React Native mobile application which is a part of a bigger project which consists of 3 apps such as Users App, Riders(Drivers) App and Admin Panel. This app is built for the driver who pickup and drop the workers to and fro their workplace. Features are built considering the usability and user experience of the driver. ",
    note: "**Some parts of the video is hidden because of security reasons. Github code is not available for this project because it's a company project but I can show the code locally.",

    techs: [
      "React Native",
      "Expo for Development",
      "Firebase Realtime Database",
      "Firebase Authentication",
      "React Navigation for routing",
      "React Native Bottom Tabs",
      "Stripe for Payment",
    ],
    features: [
      "Rider's assigned jobs are shown inside the jobs section",
      "Rider's current assigned job is shown in the homepage as well.",
      "Job consists of all the job details such as timing, people to pickup, location and assigned vehicle is also shown",
      "Rider view the route (opens in Google map)",
      "Rider can mark the attendance of workers",
      "Rider can Live Chat with customer care",
      "Rider can send queries through Help Desk",
      "Ongoing, Closed Chat History is shown using green and red",
      "Ongoing, Closed help queries is shown with conditional banner showing status",
      "Rider can request fuel fill by choosing his assigned vehicle from list",
      "Rider can see his fuel fill requests history with status banner conditionally in real time",
    ],
    tags: [
      "React Native",
      "Yelp Fusion API",
      "Redux",
      "React Navigation",
      "Expo",
      "Firebase Firestore",
    ],
    github: "",
  },

  {
    id: "project2",
    name: "Food Delivery App (React Native)",
    imageURL: [
      "/assets/projects/foodash1.jpeg",
      "/assets/projects/foodash2.jpeg",
      "/assets/projects/foodash3.jpeg",
      "/assets/projects/foodash4.jpeg",
    ],
    videoURL: "/assets/foodashvid.mp4",
    description:
      "FoodDash is a demo React Native mobile application that allows users to discover and order food from local restaurants. It leverages the power of the Yelp Fusion API to provide real-time restaurant data, reviews, and menu information.",
    techs: [
      "React Native",
      "Expo for Development",
      "Yelp Fusion API",
      "Redux for state management",
      "React Navigation for routing",
      "Firebase Firestore to store order data",
      "Lottie to show animations",
    ],
    features: [
      "User can select different cities",
      "User can view, like, different restaurants in a particular city",
      "Ratings, Menu, Price range(cheap to expensive) of a restaurant is shown",
      "User can order food",
      "User Add to Cart",
      "Increment/Decrement Quantity",
      "Price and Total price changes accordingly",
      "Remove a selected item from cart",
      "More features soon",
    ],
    tags: [
      "React Native",
      "Yelp Fusion API",
      "Redux",
      "React Navigation",
      "Expo",
      "Firebase Firestore",
    ],
    github: "https://github.com/irf0/foodash-react-native-app",
  },

  {
    id: "project3",
    name: "Ecommerce App for Shoes (React Native)",
    imageURL: [
      "/assets/projects/shoe1.jpeg",
      "/assets/projects/shoe2.jpeg",
      "/assets/projects/shoe3.jpeg",
      "/assets/projects/shoe4.jpeg",
      "/assets/projects/shoe5.jpeg",
      "/assets/projects/shoe6.jpeg",
      "/assets/projects/shoe7.jpeg",
      "/assets/projects/shoe8.jpeg",
      "/assets/projects/shoe9.jpeg",
      "/assets/projects/shoe10.jpeg",
    ],
    videoURL: "/assets/nikevid.mp4",
    description:
      "Impulse Sneaxx is a cutting-edge mobile e-commerce application designed for shoe enthusiasts. Developed using the MERN (MongoDB, Express.js, React Native, Node.js) stack, this app provides a seamless and user-friendly experience for buying shoes online.",

    tags: [
      "React Native",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Expo",
      "React Navigation",
      "Redux",
      "REST API",
      "Stripe",
    ],
    techs: [
      "React Native",
      "Expo for development",
      "React Navigation",
      "React Async Storage for local storage",
      "Reduxjs toolkit for state management",
      "REST API",
      "MongoDB for database",
      "NodeJS/ExpressJS for backend",
      "Stripe for Payment",
    ],

    features: [
      "User can view, swipe left/right (carousel) products",
      "User can select and add to cart",
      "User can search and select a product",
      "User can Increment/Decrement quantity",
      "Price and Total price changes accordingly",
      "User can pay using Stripe secure payment",
      "User gets a tracking number after order completes",
      "User can see the tracking details directly or by entering the order id",
    ],
    github: "https://github.com/irf0/NikeFrontend",
  },
];
