export default [
  {
    id: "project1",
    name: "Food Delivery App (React Native)",
    imageURL: [
      "/assets/projects/foodash1.jpeg",
      "/assets/projects/foodash2.jpeg",
      "/assets/projects/foodash3.jpeg",
      "/assets/projects/foodash4.jpeg",
    ],
    videoURL: "/assets/foodashvid.mp4",
    description:
      "FoodDash is a demo React Native mobile application that allows users to discover and order food from local restaurants. It leverages the power of the Yelp Fusion API to provide real-time restaurant data, reviews, and menu information.",
    techs: [
      "React Native",
      "Yelp Fusion API",
      "Redux for state management",
      "React Navigation for routing",
      "Firebase for user authentication",
      "Axios for API requests",
    ],
    tags: [
      "React Native",
      "Yelp Fusion API",
      "Redux",
      "React Navigation",
      "Expo",
      "Firebase",
    ],
    github: "https://github.com/irf0/foodash-react-native-app",
  },
  {
    id: "project2",
    name: "Shoe Selling Ecommerce App (React Native)",
    imageURL: [
      "/assets/projects/shoe1.jpeg",
      "/assets/projects/shoe2.jpeg",
      "/assets/projects/shoe3.jpeg",
      "/assets/projects/shoe4.jpeg",
      "/assets/projects/shoe5.jpeg",
      "/assets/projects/shoe6.jpeg",
      "/assets/projects/shoe7.jpeg",
      "/assets/projects/shoe8.jpeg",
      "/assets/projects/shoe9.jpeg",
      "/assets/projects/shoe10.jpeg",
    ],
    videoURL: "/assets/nikevid.mp4",
    description:
      "Impulse Sneaxx is a cutting-edge mobile e-commerce application designed for shoe enthusiasts. Developed using the MERN (MongoDB, Express.js, React Native, Node.js) stack, this app provides a seamless and user-friendly experience for buying shoes online.",

    tags: [
      "React Native",
      "NodeJS",
      "ExpressJS",
      "MongoDB",
      "Expo",
      "React Navigation",
      "Redux",
      "Axios API",
      "Stripe",
    ],
    techs: [
      "React Native",
      "Yelp Fusion API",
      "Redux for state management",
      "React Navigation for routing",
      "Firebase for user authentication",
      "Axios for API requests",
    ],
    github: "https://github.com/irf0/NikeFrontend",
  },
];
